package de.karl_der_iii.economymc.service;

import java.util.HashMap;
import java.util.Map;

public final class LanguageManager {
    private static final Map<String, Map<String, String>> LANG = new HashMap<>();

    static {
        Map<String, String> en = new HashMap<>();

        en.put("help.header", "§6EconomyMC Commands");
        en.put("help.plots", "§e/ec plots §7- opens the plots menu");
        en.put("help.shop", "§e/ec shop §7- opens the shop menu");
        en.put("help.jobs", "§e/ec jobs §7- opens the jobs menu");
        en.put("help.checks", "§e/ec checks §7- opens the checks menu");
        en.put("help.history", "§e/ec history §7- opens the payment history");
        en.put("help.daily", "§e/ec daily §7- claims the daily reward");
        en.put("help.pay", "§e/ec pay <player/treasury> <amount> §7- sends money");
        en.put("help.servermode", "§e/ec servermode §7- opens server mode");
        en.put("help.adminmode", "§e/ec adminmode §7- opens admin mode");
        en.put("help.admin", "§e/ec admin ... §7- capital and account management");
        en.put("help.language", "§7Languages: German, English, Polish, French, Spanish, Portuguese, Russian, Turkish, Chinese, Japanese");

        en.put("cmd.only_players", "Only players can use this command.");
        en.put("msg.shop_disabled", "§cShop is disabled by admin.");
        en.put("msg.jobs_disabled", "§cJobs are disabled by admin.");
        en.put("msg.checks_disabled", "§cChecks are disabled by admin.");
        en.put("msg.servermode_disabled", "§cServer mode is disabled by admin.");

        en.put("admin.language", "§7Language: English");
        en.put("admin.language.toggle", "§bSwitch language");
        en.put("admin.mode.title", "EconomyMC Admin Mode");
        en.put("admin.on", "ON");
        en.put("admin.off", "OFF");
        en.put("admin.jobs", "Jobs");
        en.put("admin.checks", "Checks");
        en.put("admin.shop", "Shop");
        en.put("admin.plot_market", "Plot Market");
        en.put("admin.server_mode", "Server Mode");
        en.put("admin.min_tax", "§7Min Tax");
        en.put("admin.min_overdue", "§7Min Overdue");
        en.put("admin.min_cancel", "§7Min Cancel");
        en.put("admin.auto", "Auto");
        en.put("admin.manual", "Manual");

        en.put("common.close", "§cClose");
        en.put("common.back", "§cBack");
        en.put("common.next", "§7Next Page");
        en.put("common.previous", "§7Previous Page");
        en.put("common.confirm", "§aConfirm");
        en.put("common.cancel", "§cCancel");
        en.put("common.create", "§aCreate");
        en.put("common.edit", "§eEdit");
        en.put("common.price", "§6Price");
        en.put("common.description", "§7Description");
        en.put("common.status", "§7Status");
        en.put("common.page", "§7Page ");
        en.put("common.seller", "§7Seller");
        en.put("common.amount", "§7Amount");
        en.put("common.click_to_view", "§7Click to view");
        en.put("common.publish", "§bPublish");
        en.put("common.sell", "§aSell");
        en.put("common.treasury", "Treasury");
        en.put("common.location", "§7Location");
        en.put("common.chunks", "§7Chunks");

        en.put("menu.player.balance", "§6Balance: $%d");
        en.put("menu.player.normal", "§7Normal Credits: %d");
        en.put("menu.player.capital", "§7Capital Credits: %d");

        en.put("plots.menu.title", "EconomyMC Plots");
        en.put("plots.position.capital", "§6Current Position: Capital Zone");
        en.put("plots.position.normal", "§7Current Position: Normal Zone");
        en.put("plots.buy.normal", "§eBuy Normal Claim Credits");
        en.put("plots.buy.capital", "§6Buy Capital Claim Credits");
        en.put("plots.create.sale", "§aCreate Sale Listing");
        en.put("plots.market", "§3Market Listings");
        en.put("plots.mine", "§bMy Plots");
        en.put("plots.sales", "§dMy Sales");
        en.put("plots.history", "§aOpen History");
        en.put("plots.buy.normal.fail", "§cYou do not have enough money for a normal claim credit.");
        en.put("plots.buy.normal.ok", "§aBought 1 normal claim credit.");
        en.put("plots.buy.capital.fail", "§cYou do not have enough money for a capital claim credit.");
        en.put("plots.buy.capital.ok", "§aBought 1 capital claim credit.");

        en.put("shop.menu.title", "EconomyMC Shop");
        en.put("shop.sell.title", "EconomyMC Sell Item");
        en.put("shop.bundle", "§dShop Bundle");
        en.put("shop.base_price", "§6Base Price: $");
        en.put("shop.tax", "§cTax: $");
        en.put("shop.total", "§aTotal: $");
        en.put("shop.stacks_inside", "§7Stacks inside: ");
        en.put("shop.total_items", "§7Total items: ");
        en.put("shop.and_more", "§8...and more");
        en.put("shop.sell.set_price", "§eSet Price");
        en.put("shop.sell.publish", "§aPublish");
        en.put("shop.sell.put_items_first", "§cPut items in first.");
        en.put("shop.sell.published", "§aShop listing published.");
        en.put("shop.input.enter_price", "§eEnter the shop price in chat now.");
        en.put("shop.input.no_draft", "§cNo shop draft selected.");
        en.put("shop.input.price_positive", "§cPrice must be above 0.");
        en.put("shop.input.price_set", "§aShop price set to $");
        en.put("shop.input.invalid_number", "§cThat is not a valid number.");
        en.put("shop.listing_missing", "Listing no longer exists");
        en.put("shop.withdraw", "§cWithdraw Listing");
        en.put("shop.buy", "§aBuy");
        en.put("shop.withdrawn", "§aListing withdrawn.");
        en.put("shop.not_enough_money", "§cYou do not have enough money.");
        en.put("shop.bought", "§aItem(s) bought for $%d §7(Tax: $%d)");

        en.put("jobs.menu.title", "EconomyMC Jobs");
        en.put("jobs.server.title", "EconomyMC Server Jobs");
        en.put("job.detail.title", "EconomyMC Job Details");
        en.put("jobs.add", "§aAdd Job");
        en.put("jobs.create_hint", "§7Create jobs in the correct menu");
        en.put("jobs.status.open", "§aOpen");
        en.put("jobs.status.opens_at", "§eOpens ");
        en.put("jobs.status.in_progress", "§6In Progress: ");
        en.put("jobs.status.completed", "§bCompleted");
        en.put("jobs.status.confirmed", "§aConfirmed");
        en.put("jobs.status.cancelled", "§cCancelled");
        en.put("jobs.status.failed", "§4Failed");
        en.put("jobs.reward", "§6Reward: $");
        en.put("jobs.created_by", "§7Created by: ");
        en.put("jobs.description", "§7Description: ");
        en.put("jobs.due_in", "§7Due in: ");
        en.put("jobs.day_suffix", " day(s)");
        en.put("jobs.current_payout", "§7Current payout: $");
        en.put("jobs.unavailable", "§cJob no longer available");
        en.put("jobs.accept", "§aAccept Job");
        en.put("jobs.accept_server", "§aAccept Server Job");
        en.put("jobs.available_at", "§eAvailable at ");
        en.put("jobs.withdraw", "§cWithdraw Job");
        en.put("jobs.mark_completed", "§bMark as Completed");
        en.put("jobs.cancel_job", "§cCancel Job");
        en.put("jobs.in_progress_by", "§7In Progress by ");
        en.put("jobs.confirm_job", "§aConfirm Job");
        en.put("jobs.waiting_confirmation", "§7Waiting for confirmation");
        en.put("jobs.input.title", "§eEnter the job title in chat now.");
        en.put("jobs.input.server_title", "§eEnter the server job title in chat now.");
        en.put("jobs.input.description", "§eEnter the job description in chat now.");
        en.put("jobs.input.reward", "§eEnter the reward amount in chat now.");
        en.put("jobs.input.due_days", "§eEnter the due time in full days now.");
        en.put("jobs.input.invalid_number", "§cThat is not a valid number.");
        en.put("jobs.input.reward_positive", "§cReward must be above 0.");
        en.put("jobs.input.days_positive", "§cDue days must be above 0.");
        en.put("jobs.input.treasury_missing", "§cThe treasury does not have enough money for this server job.");
        en.put("jobs.input.player_missing_money", "§cYou do not have enough money to create this job.");
        en.put("jobs.input.created", "§aJob created.");
        en.put("jobs.error.accept_yet", "§cThis job cannot be accepted yet.");
        en.put("jobs.error.not_open", "§cThis job is no longer open.");
        en.put("jobs.error.own_job", "§cYou cannot accept your own job.");
        en.put("jobs.error.withdraw", "§cCould not withdraw job.");
        en.put("jobs.error.complete", "§cCould not mark job as completed.");
        en.put("jobs.error.confirm", "§cCould not confirm job.");
        en.put("jobs.error.cancel", "§cCould not cancel job.");
        en.put("jobs.msg.accepted", "§aYou accepted the job.");
        en.put("jobs.msg.accepted_server", "§aYou accepted the server job.");
        en.put("jobs.msg.withdrawn", "§aJob withdrawn.");
        en.put("jobs.msg.withdrawn_server", "§aServer job withdrawn.");
        en.put("jobs.msg.completed", "§aJob marked as completed.");
        en.put("jobs.msg.confirmed", "§aJob confirmed.");
        en.put("jobs.msg.cancelled_penalty", "§cJob cancelled. Penalty: $");

        en.put("checks.menu.title", "EconomyMC Checks");
        en.put("check.redeem.title", "EconomyMC Redeem Check");
        en.put("checks.create", "§aCreate Check");
        en.put("checks.creator", "§eCreator: ");
        en.put("checks.amount", "§6Amount: $");
        en.put("checks.redeem", "§aRedeem");
        en.put("checks.redeemed", "§7Already redeemed");
        en.put("checks.not_found", "§cCheck not found");
        en.put("checks.no_longer", "§cThis check can no longer be redeemed.");
        en.put("checks.entry", "%sCheck $%d - %s");
        en.put("checks.input.amount", "§eEnter the check amount in chat now.");
        en.put("checks.input.code", "§eEnter the check code in chat now.");
        en.put("checks.input.invalid_number", "§cThat is not a valid number.");
        en.put("checks.input.amount_positive", "§cAmount must be above 0.");
        en.put("checks.input.not_enough", "§cYou do not have enough money.");
        en.put("checks.input.created", "§aCheck created.");
        en.put("checks.input.invalid_code", "§cInvalid code or check already redeemed.");
        en.put("checks.input.redeemed_success", "§aCheck redeemed successfully.");

        en.put("market.menu.title", "EconomyMC Market");
        en.put("market.entry", "%s §7| $%d | %d chunks");
        en.put("market.back", "§cBack");

        en.put("myplots.menu.title", "My Plots");
        en.put("myplots.entry", "%s%s §7| %d chunks | %s");
        en.put("myplots.info", "§7Click a plot to create a sale draft");
        en.put("myplots.already_listed", "§cThis plot is already listed in the market.");
        en.put("myplots.already_draft", "§cThis plot already has a sale draft.");
        en.put("myplots.draft_selected", "§aSale draft selected: %s");
        en.put("myplots.edit_later", "Edit later");

        en.put("mysales.menu.title", "My Sales");
        en.put("mysales.entry", "%s%s §7| $%d");

        en.put("listing.menu.title", "EconomyMC Listing");
        en.put("listing.missing", "§cListing no longer exists");
        en.put("listing.price", "§6Price: $%d");
        en.put("listing.description", "§7Description: %s");
        en.put("listing.location", "§7Location: %s");
        en.put("listing.building", "§7Built on plot: %s");
        en.put("listing.reason", "§7Reason: %s");
        en.put("listing.chunks", "§7Chunks: %d");
        en.put("listing.buy", "§aBuy");
        en.put("listing.not.exists", "§cListing no longer exists.");
        en.put("listing.buy.own", "§cYou cannot buy your own listing.");
        en.put("listing.not.enough", "§cYou do not have enough money.");
        en.put("listing.buy.success", "§aBought listing: %s");

        en.put("sale.menu.title", "EconomyMC Create Sale Listing");
        en.put("sale.no_draft", "§cNo sale draft selected");
        en.put("sale.selected_capital", "§6Selected Capital Plot");
        en.put("sale.selected_plot", "§7Selected Plot");
        en.put("sale.plot", "§bPlot: ");
        en.put("sale.chunks", " Chunks");
        en.put("sale.set_price", "§eSet Price: $");
        en.put("sale.set_description", "§7Set Description");
        en.put("sale.set_built", "§7Set Built On Plot");
        en.put("sale.set_justification", "§7Set Price Justification");
        en.put("sale.negotiable", "§aNegotiable");
        en.put("sale.fixed", "§6Fixed Price");
        en.put("sale.publish", "§bPublish Listing");
        en.put("sale.location", "§7Location: ");
        en.put("sale.clear_draft", "§cClear Draft");
        en.put("sale.already_listed", "§cThis plot is already listed in the market.");
        en.put("sale.published", "§aListing published.");
        en.put("sale.cleared", "§aSale draft cleared.");

        en.put("server.mode.title", "EconomyMC Server Mode");
        en.put("server.treasury_balance", "§6Treasury: $");
        en.put("server.tax_minus", "§cTax -1%");
        en.put("server.tax_plus", "§aTax +1%");
        en.put("server.tax_rate", "§7Tax Rate: ");
        en.put("server.auto_tax", "Auto Tax");
        en.put("server.overdue_minus", "§cOverdue -1%");
        en.put("server.overdue_plus", "§aOverdue +1%");
        en.put("server.overdue_penalty", "§7Overdue Penalty: ");
        en.put("server.cancel_minus", "§cCancel -1%");
        en.put("server.cancel_plus", "§aCancel +1%");
        en.put("server.cancel_penalty", "§7Cancel Penalty: ");
        en.put("server.days_minus", "§cDays -1");
        en.put("server.days_plus", "§aDays +1");
        en.put("server.max_overdue_days", "§7Max Overdue Days: ");
        en.put("server.start_hour_minus", "§cStart Hour -1");
        en.put("server.start_hour_plus", "§aStart Hour +1");
        en.put("server.job_open_hour", "§7Job Open Hour: ");
        en.put("server.create_job", "§aCreate Server Job");
        en.put("server.open_jobs", "§bOpen Server Jobs");
        en.put("server.info", "§7Treasury, jobs and taxes");

        en.put("history.title", "EconomyMC History");
        en.put("history.empty", "§7No entries yet.");
        en.put("history.mine", "§bMy History");
        en.put("history.treasury", "§6Treasury History");
        en.put("history.open", "§aOpen History");
        en.put("history.pay.sent", "§aPay to %s: $%d");
        en.put("history.pay.received", "§aPay from %s: $%d");
        en.put("history.daily", "§eDaily reward: $%d");
        en.put("history.check.create", "§dCreated check: $%d");
        en.put("history.check.redeem", "§dRedeemed check: $%d");
        en.put("history.job.reward", "§bJob payout: $%d");
        en.put("history.job.refund", "§6Job refund: $%d");
        en.put("history.treasury.tax", "§6Tax received: $%d");
        en.put("history.admin.set", "§cAdmin set balance: $%d");

        en.put("bank.title", "EconomyMC Bank");
        en.put("bank.target.server", "Server");
        en.put("bank.target.player", "Player");
        en.put("bank.target.all", "All Players");
        en.put("bank.command.request", "Create Loan Request");
        en.put("bank.command.offer", "Create Loan Offer");
        en.put("bank.command.accept", "Accept Loan");
        en.put("bank.command.repay", "Repay Loan");
        en.put("bank.loan_id", "Loan ID");

        en.put("help.bank", "§e/ec bank §7- opens the bank menu");
        en.put("bank.command.list", "§e/ec bank list §7- shows open loan requests and offers");
        en.put("bank.invalid_target", "§cUnknown target player.");
        en.put("bank.not_enough_money", "§cYou do not have enough money.");
        en.put("bank.not_found", "§cLoan not found.");
        en.put("bank.request.created", "§aLoan request created.");
        en.put("bank.offer.created", "§aLoan offer created.");
        en.put("bank.accepted", "§aLoan accepted.");
        en.put("bank.repaid", "§aLoan repaid.");
        en.put("history.loan.request", "§bLoan request: $%d");
        en.put("history.loan.funded", "§aLoan funded: $%d");
        en.put("history.loan.received", "§aLoan received: $%d");
        en.put("history.loan.repaid", "§6Loan repaid: $%d");
        en.put("history.loan.interest", "§eInterest paid: $%d");
        en.put("draft.input.price", "§eEnter the price in chat now.");
        en.put("draft.input.description", "§eEnter the description in chat now.");
        en.put("draft.input.built", "§eEnter what is built on the plot in chat now.");
        en.put("draft.input.justification", "§eEnter the price justification in chat now.");
        en.put("draft.input.no_draft", "§cNo sale draft selected.");
        en.put("draft.input.price_positive", "§cPrice must be above 0.");
        en.put("draft.input.invalid_number", "§cThat is not a valid number.");
        en.put("draft.input.price_set", "§aDraft price set to $%d");
        en.put("draft.input.description_set", "§aDraft description updated.");
        en.put("draft.input.built_set", "§aDraft built-on-plot text updated.");
        en.put("draft.input.justification_set", "§aDraft price justification updated.");
        en.put("daily.already", "§cDaily already claimed for today. Come back in %dh %dm.");
        en.put("daily.claimed", "§aYou claimed your daily $100.");
        en.put("pay.known_or_treasury", "§cOnly known players or Treasury can receive money.");
        en.put("pay.self", "§cYou cannot pay yourself.");
        en.put("pay.not_enough", "§cYou do not have enough money.");
        en.put("pay.sent", "§aYou paid $%d to %s.");
        en.put("pay.received", "§aYou received $%d from %s.");
        en.put("admin.pos1_set", "§aCapital pos1 set to: %d, %d, %d");
        en.put("admin.pos2_set", "§aCapital pos2 set to: %d, %d, %d");
        en.put("admin.pos_missing", "§cSet /ec admin pos1 and /ec admin pos2 first.");
        en.put("admin.capital_saved", "§aCapital area saved.");
        en.put("admin.capital_cleared", "§aCapital area cleared.");

        LANG.put("en_us", en);

        Map<String, String> de = new HashMap<>(en);
        de.put("help.header", "§6EconomyMC Befehle");
        de.put("help.plots", "§e/ec plots §7- öffnet das Grundstücksmenü");
        de.put("help.shop", "§e/ec shop §7- öffnet das Shop-Menü");
        de.put("help.jobs", "§e/ec jobs §7- öffnet das Jobs-Menü");
        de.put("help.checks", "§e/ec checks §7- öffnet das Checks-Menü");
        de.put("help.history", "§e/ec history §7- öffnet den Zahlungsverlauf");
        de.put("help.daily", "§e/ec daily §7- holt die tägliche Belohnung");
        de.put("help.pay", "§e/ec pay <Spieler/Treasury> <Betrag> §7- sendet Geld");
        de.put("help.servermode", "§e/ec servermode §7- öffnet den Servermodus");
        de.put("help.adminmode", "§e/ec adminmode §7- öffnet den Adminmodus");
        de.put("help.admin", "§e/ec admin ... §7- Hauptstadt und Kontoverwaltung");
        de.put("help.language", "§7Sprachen: Deutsch, Englisch, Polnisch, Französisch, Spanisch, Portugiesisch, Russisch, Türkisch, Chinesisch, Japanisch");

        de.put("cmd.only_players", "Nur Spieler können diesen Befehl benutzen.");
        de.put("msg.shop_disabled", "§cShop ist vom Admin deaktiviert.");
        de.put("msg.jobs_disabled", "§cJobs sind vom Admin deaktiviert.");
        de.put("msg.checks_disabled", "§cChecks sind vom Admin deaktiviert.");
        de.put("msg.servermode_disabled", "§cServer-Modus ist vom Admin deaktiviert.");

        de.put("admin.language", "§7Sprache: Deutsch");
        de.put("admin.language.toggle", "§bSprache wechseln");
        de.put("admin.mode.title", "EconomyMC Adminmodus");
        de.put("admin.on", "AN");
        de.put("admin.off", "AUS");
        de.put("admin.jobs", "Jobs");
        de.put("admin.checks", "Checks");
        de.put("admin.shop", "Shop");
        de.put("admin.plot_market", "Grundstücksmarkt");
        de.put("admin.server_mode", "Servermodus");
        de.put("admin.min_tax", "§7Min. Steuer");
        de.put("admin.min_overdue", "§7Min. Überzug");
        de.put("admin.min_cancel", "§7Min. Abbruch");
        de.put("admin.auto", "Auto");
        de.put("admin.manual", "Manuell");

        de.put("common.close", "§cSchließen");
        de.put("common.back", "§cZurück");
        de.put("common.next", "§7Nächste Seite");
        de.put("common.previous", "§7Vorherige Seite");
        de.put("common.confirm", "§aBestätigen");
        de.put("common.cancel", "§cAbbrechen");
        de.put("common.create", "§aErstellen");
        de.put("common.edit", "§eBearbeiten");
        de.put("common.price", "§6Preis");
        de.put("common.description", "§7Beschreibung");
        de.put("common.status", "§7Status");
        de.put("common.page", "§7Seite ");
        de.put("common.seller", "§7Verkäufer");
        de.put("common.amount", "§7Menge");
        de.put("common.click_to_view", "§7Zum Anzeigen klicken");
        de.put("common.publish", "§bVeröffentlichen");
        de.put("common.sell", "§aVerkaufen");
        de.put("common.treasury", "Treasury");
        de.put("common.location", "§7Ort");
        de.put("common.chunks", "§7Chunks");

        de.put("menu.player.balance", "§6Kontostand: $%d");
        de.put("menu.player.normal", "§7Normale Credits: %d");
        de.put("menu.player.capital", "§7Hauptstadt-Credits: %d");

        de.put("shop.listing_missing", "Angebot existiert nicht mehr");
        de.put("shop.withdraw", "§cAngebot zurücknehmen");
        de.put("shop.buy", "§aKaufen");
        de.put("shop.withdrawn", "§aAngebot zurückgenommen.");
        de.put("shop.not_enough_money", "§cDu hast nicht genug Geld.");
        de.put("shop.bought", "§aItem(s) gekauft für $%d §7(Steuer: $%d)");

        de.put("checks.entry", "%sCheck $%d - %s");
        de.put("checks.input.amount", "§eGib jetzt den Check-Betrag im Chat ein.");
        de.put("checks.input.code", "§eGib jetzt den Check-Code im Chat ein.");
        de.put("checks.input.invalid_number", "§cDas ist keine gültige Zahl.");
        de.put("checks.input.amount_positive", "§cDer Betrag muss über 0 liegen.");
        de.put("checks.input.not_enough", "§cDu hast nicht genug Geld.");
        de.put("checks.input.created", "§aCheck erstellt.");
        de.put("checks.input.invalid_code", "§cUngültiger Code oder Check bereits eingelöst.");
        de.put("checks.input.redeemed_success", "§aCheck erfolgreich eingelöst.");

        de.put("market.menu.title", "EconomyMC Markt");
        de.put("market.entry", "%s §7| $%d | %d Chunks");
        de.put("market.back", "§cZurück");

        de.put("myplots.menu.title", "Meine Grundstücke");
        de.put("myplots.entry", "%s%s §7| %d Chunks | %s");
        de.put("myplots.info", "§7Klicke ein Grundstück an, um einen Verkaufsentwurf zu erstellen");
        de.put("myplots.already_listed", "§cDieses Grundstück ist bereits auf dem Markt gelistet.");
        de.put("myplots.already_draft", "§cDieses Grundstück hat bereits einen Verkaufsentwurf.");
        de.put("myplots.draft_selected", "§aVerkaufsentwurf ausgewählt: %s");
        de.put("myplots.edit_later", "Später bearbeiten");

        de.put("mysales.menu.title", "Meine Verkäufe");
        de.put("mysales.entry", "%s%s §7| $%d");

        de.put("listing.menu.title", "EconomyMC Angebot");
        de.put("listing.missing", "§cAngebot existiert nicht mehr");
        de.put("listing.price", "§6Preis: $%d");
        de.put("listing.description", "§7Beschreibung: %s");
        de.put("listing.location", "§7Ort: %s");
        de.put("listing.building", "§7Bebauung: %s");
        de.put("listing.reason", "§7Begründung: %s");
        de.put("listing.chunks", "§7Chunks: %d");
        de.put("listing.buy", "§aKaufen");
        de.put("listing.not.exists", "§cAngebot existiert nicht mehr.");
        de.put("listing.buy.own", "§cDu kannst dein eigenes Angebot nicht kaufen.");
        de.put("listing.not.enough", "§cDu hast nicht genug Geld.");
        de.put("listing.buy.success", "§aAngebot gekauft: %s");

        de.put("sale.menu.title", "EconomyMC Verkaufsangebot erstellen");
        de.put("sale.no_draft", "§cKein Verkaufsentwurf ausgewählt");
        de.put("sale.selected_capital", "§6Ausgewähltes Hauptstadt-Grundstück");
        de.put("sale.selected_plot", "§7Ausgewähltes Grundstück");
        de.put("sale.plot", "§bGrundstück: ");
        de.put("sale.chunks", " Chunks");
        de.put("sale.set_price", "§ePreis setzen: $");
        de.put("sale.set_description", "§7Beschreibung setzen");
        de.put("sale.set_built", "§7Bebauung setzen");
        de.put("sale.set_justification", "§7Preisbegründung setzen");
        de.put("sale.negotiable", "§aVerhandelbar");
        de.put("sale.fixed", "§6Festpreis");
        de.put("sale.publish", "§bAngebot veröffentlichen");
        de.put("sale.location", "§7Ort: ");
        de.put("sale.clear_draft", "§cEntwurf löschen");
        de.put("sale.already_listed", "§cDieses Grundstück ist bereits auf dem Markt gelistet.");
        de.put("sale.published", "§aAngebot veröffentlicht.");
        de.put("sale.cleared", "§aVerkaufsentwurf gelöscht.");

        de.put("plots.menu.title", "EconomyMC Grundstücke");
        de.put("plots.position.capital", "§6Aktuelle Position: Hauptstadt-Zone");
        de.put("plots.position.normal", "§7Aktuelle Position: Normale Zone");
        de.put("plots.buy.normal", "§eNormale Claim-Credits kaufen");
        de.put("plots.buy.capital", "§6Hauptstadt-Claim-Credits kaufen");
        de.put("plots.create.sale", "§aVerkaufsangebot erstellen");
        de.put("plots.market", "§3Marktangebote");
        de.put("plots.mine", "§bMeine Grundstücke");
        de.put("plots.sales", "§dMeine Verkäufe");
        de.put("plots.history", "§aVerlauf öffnen");
        de.put("plots.buy.normal.fail", "§cDu hast nicht genug Geld für einen normalen Claim-Credit.");
        de.put("plots.buy.normal.ok", "§a1 normaler Claim-Credit gekauft.");
        de.put("plots.buy.capital.fail", "§cDu hast nicht genug Geld für einen Hauptstadt-Claim-Credit.");
        de.put("plots.buy.capital.ok", "§a1 Hauptstadt-Claim-Credit gekauft.");

        de.put("server.mode.title", "EconomyMC Servermodus");
        de.put("server.treasury_balance", "§6Treasury: $");
        de.put("server.tax_minus", "§cSteuer -1%");
        de.put("server.tax_plus", "§aSteuer +1%");
        de.put("server.tax_rate", "§7Steuersatz: ");
        de.put("server.auto_tax", "Automatische Steuer");
        de.put("server.overdue_minus", "§cÜberzug -1%");
        de.put("server.overdue_plus", "§aÜberzug +1%");
        de.put("server.overdue_penalty", "§7Überzugsgebühr: ");
        de.put("server.cancel_minus", "§cAbbruch -1%");
        de.put("server.cancel_plus", "§aAbbruch +1%");
        de.put("server.cancel_penalty", "§7Abbruchgebühr: ");
        de.put("server.days_minus", "§cTage -1");
        de.put("server.days_plus", "§aTage +1");
        de.put("server.max_overdue_days", "§7Max. Überzugstage: ");
        de.put("server.start_hour_minus", "§cStartstunde -1");
        de.put("server.start_hour_plus", "§aStartstunde +1");
        de.put("server.job_open_hour", "§7Job-Startstunde: ");
        de.put("server.create_job", "§aServer-Job erstellen");
        de.put("server.open_jobs", "§bServer-Jobs öffnen");
        de.put("server.info", "§7Treasury, Jobs und Steuern");

        de.put("history.title", "EconomyMC Verlauf");
        de.put("history.empty", "§7Noch keine Einträge vorhanden.");
        de.put("history.mine", "§bMein Verlauf");
        de.put("history.treasury", "§6Treasury-Verlauf");
        de.put("history.open", "§aVerlauf öffnen");
        de.put("history.pay.sent", "§aÜberweisung an %s: $%d");
        de.put("history.pay.received", "§aÜberweisung von %s: $%d");
        de.put("history.daily", "§eTägliche Belohnung: $%d");
        de.put("history.check.create", "§dCheck erstellt: $%d");
        de.put("history.check.redeem", "§dCheck eingelöst: $%d");
        de.put("history.job.reward", "§bJob-Auszahlung: $%d");
        de.put("history.job.refund", "§6Job-Rückzahlung: $%d");
        de.put("history.treasury.tax", "§6Steuer erhalten: $%d");
        de.put("history.admin.set", "§cAdmin setzte Guthaben: $%d");

        de.put("bank.title", "EconomyMC Bank");
        de.put("bank.target.server", "Server");
        de.put("bank.target.player", "Spieler");
        de.put("bank.target.all", "Alle Spieler");
        de.put("bank.command.request", "Kreditanfrage erstellen");
        de.put("bank.command.offer", "Kreditangebot erstellen");
        de.put("bank.command.accept", "Kredit annehmen");
        de.put("bank.command.repay", "Kredit zurückzahlen");
        de.put("bank.loan_id", "Kredit-ID");

        de.put("help.bank", "§e/ec bank §7- öffnet das Bank-Menü");
        de.put("bank.command.list", "§e/ec bank list §7- zeigt offene Kreditanfragen und Angebote");
        de.put("bank.invalid_target", "§cUnbekannter Zielspieler.");
        de.put("bank.not_enough_money", "§cDu hast nicht genug Geld.");
        de.put("bank.not_found", "§cKredit nicht gefunden.");
        de.put("bank.request.created", "§aKreditanfrage erstellt.");
        de.put("bank.offer.created", "§aKreditangebot erstellt.");
        de.put("bank.accepted", "§aKredit angenommen.");
        de.put("bank.repaid", "§aKredit zurückgezahlt.");
        de.put("history.loan.request", "§bKreditanfrage: $%d");
        de.put("history.loan.funded", "§aKredit finanziert: $%d");
        de.put("history.loan.received", "§aKredit erhalten: $%d");
        de.put("history.loan.repaid", "§6Kredit zurückgezahlt: $%d");
        de.put("history.loan.interest", "§eZinsen bezahlt: $%d");
        de.put("draft.input.price", "§eGib jetzt den Preis im Chat ein.");
        de.put("draft.input.description", "§eGib jetzt die Beschreibung im Chat ein.");
        de.put("draft.input.built", "§eGib jetzt ein, was auf dem Grundstück gebaut ist.");
        de.put("draft.input.justification", "§eGib jetzt die Preisbegründung im Chat ein.");
        de.put("draft.input.no_draft", "§cKein Verkaufsentwurf ausgewählt.");
        de.put("draft.input.price_positive", "§cDer Preis muss über 0 liegen.");
        de.put("draft.input.invalid_number", "§cDas ist keine gültige Zahl.");
        de.put("draft.input.price_set", "§aEntwurfspreis gesetzt auf $%d");
        de.put("draft.input.description_set", "§aEntwurfsbeschreibung aktualisiert.");
        de.put("draft.input.built_set", "§aText für Bebauung aktualisiert.");
        de.put("draft.input.justification_set", "§aPreisbegründung aktualisiert.");
        de.put("daily.already", "§cDaily für heute schon abgeholt. Komm in %dh %dm zurück.");
        de.put("daily.claimed", "§aDu hast dein tägliches $100 abgeholt.");
        de.put("pay.known_or_treasury", "§cNur bekannte Spieler oder das Treasury können Geld erhalten.");
        de.put("pay.self", "§cDu kannst dir nicht selbst Geld senden.");
        de.put("pay.not_enough", "§cDu hast nicht genug Geld.");
        de.put("pay.sent", "§aDu hast $%d an %s bezahlt.");
        de.put("pay.received", "§aDu hast $%d von %s erhalten.");
        de.put("admin.pos1_set", "§aCapital pos1 gesetzt auf: %d, %d, %d");
        de.put("admin.pos2_set", "§aCapital pos2 gesetzt auf: %d, %d, %d");
        de.put("admin.pos_missing", "§cSetze zuerst /ec admin pos1 und /ec admin pos2.");
        de.put("admin.capital_saved", "§aHauptstadtbereich gespeichert.");
        de.put("admin.capital_cleared", "§aHauptstadtbereich gelöscht.");

        LANG.put("de_de", de);

        Map<String, String> pl = new HashMap<>(en);
        pl.put("admin.language", "§7Język: Polski");
        pl.put("admin.mode.title", "Tryb administratora EconomyMC");
        pl.put("admin.on", "WŁ");
        pl.put("admin.off", "WYŁ");
        pl.put("admin.jobs", "Zadania");
        pl.put("admin.checks", "Czeki");
        pl.put("admin.shop", "Sklep");
        pl.put("admin.plot_market", "Rynek działek");
        pl.put("admin.server_mode", "Tryb serwera");
        pl.put("admin.min_tax", "§7Min. podatek");
        pl.put("admin.min_overdue", "§7Min. kara");
        pl.put("admin.min_cancel", "§7Min. anulowanie");
        pl.put("admin.auto", "Auto");
        pl.put("admin.manual", "Ręcznie");

        pl.put("common.close", "§cZamknij");
        pl.put("common.back", "§cPowrót");
        pl.put("common.next", "§7Następna strona");
        pl.put("common.previous", "§7Poprzednia strona");
        pl.put("common.confirm", "§aPotwierdź");
        pl.put("common.cancel", "§cAnuluj");
        pl.put("common.create", "§aUtwórz");
        pl.put("common.edit", "§eEdytuj");
        pl.put("common.price", "§6Cena");
        pl.put("common.description", "§7Opis");
        pl.put("common.status", "§7Status");
        pl.put("common.page", "§7Strona ");
        pl.put("common.seller", "§7Sprzedawca");
        pl.put("common.amount", "§7Ilość");
        pl.put("common.click_to_view", "§7Kliknij, aby zobaczyć");
        pl.put("common.publish", "§bOpublikuj");
        pl.put("common.sell", "§aSprzedaj");

        pl.put("menu.player.balance", "§6Saldo: $%d");
        pl.put("menu.player.normal", "§7Normalne kredyty: %d");
        pl.put("menu.player.capital", "§7Kredyty stolicy: %d");

        pl.put("checks.entry", "%sCzek $%d - %s");
        pl.put("checks.input.amount", "§eWpisz teraz kwotę czeku na czacie.");
        pl.put("checks.input.code", "§eWpisz teraz kod czeku na czacie.");
        pl.put("checks.input.invalid_number", "§cTo nie jest poprawna liczba.");
        pl.put("checks.input.amount_positive", "§cKwota musi być większa niż 0.");
        pl.put("checks.input.not_enough", "§cNie masz wystarczająco pieniędzy.");
        pl.put("checks.input.created", "§aCzek utworzony.");
        pl.put("checks.input.invalid_code", "§cNieprawidłowy kod lub czek już zrealizowany.");
        pl.put("checks.input.redeemed_success", "§aCzek został pomyślnie zrealizowany.");

        pl.put("market.menu.title", "Rynek EconomyMC");
        pl.put("market.back", "§cPowrót");

        pl.put("myplots.menu.title", "Moje działki");
        pl.put("myplots.info", "§7Kliknij działkę, aby utworzyć szkic sprzedaży");
        pl.put("myplots.already_listed", "§cTa działka jest już wystawiona na rynku.");
        pl.put("myplots.already_draft", "§cTa działka ma już szkic sprzedaży.");
        pl.put("myplots.draft_selected", "§aWybrano szkic sprzedaży: %s");
        pl.put("myplots.edit_later", "Edytuj później");

        pl.put("mysales.menu.title", "Moje sprzedaże");

        pl.put("listing.menu.title", "Oferta EconomyMC");
        pl.put("listing.missing", "§cOferta już nie istnieje");
        pl.put("listing.price", "§6Cena: $%d");
        pl.put("listing.description", "§7Opis: %s");
        pl.put("listing.location", "§7Lokalizacja: %s");
        pl.put("listing.building", "§7Zabudowa: %s");
        pl.put("listing.reason", "§7Powód: %s");
        pl.put("listing.chunks", "§7Chunki: %d");
        pl.put("listing.buy", "§aKup");
        pl.put("listing.not.exists", "§cOferta już nie istnieje.");
        pl.put("listing.buy.own", "§cNie możesz kupić własnej oferty.");
        pl.put("listing.not.enough", "§cNie masz wystarczająco pieniędzy.");
        pl.put("listing.buy.success", "§aKupiono ofertę: %s");

        pl.put("plots.menu.title", "EconomyMC Działki");
        pl.put("shop.menu.title", "EconomyMC Sklep");
        pl.put("shop.sell.title", "EconomyMC Sprzedaj przedmiot");
        pl.put("shop.listing_missing", "Oferta już nie istnieje");
        pl.put("shop.withdraw", "§cWycofaj ofertę");
        pl.put("shop.buy", "§aKup");
        pl.put("shop.withdrawn", "§aOferta wycofana.");
        pl.put("shop.not_enough_money", "§cNie masz wystarczająco pieniędzy.");
        pl.put("shop.bought", "§aKupiono przedmiot(y) za $%d §7(Podatek: $%d)");

        pl.put("jobs.menu.title", "EconomyMC Zadania");
        pl.put("jobs.server.title", "Zadania serwera EconomyMC");
        pl.put("checks.menu.title", "EconomyMC Czeki");
        pl.put("check.redeem.title", "Zrealizuj czek EconomyMC");
        pl.put("server.mode.title", "Tryb serwera EconomyMC");
        pl.put("history.title", "EconomyMC Historia");
        pl.put("history.mine", "§bMoja historia");
        pl.put("history.treasury", "§6Historia skarbca");

        pl.put("bank.title", "Bank EconomyMC");
        pl.put("bank.target.server", "Serwer");
        pl.put("bank.target.player", "Gracz");
        pl.put("bank.target.all", "Wszyscy gracze");
        pl.put("bank.command.request", "Utwórz prośbę o pożyczkę");
        pl.put("bank.command.offer", "Utwórz ofertę pożyczki");
        pl.put("bank.command.accept", "Akceptuj pożyczkę");
        pl.put("bank.command.repay", "Spłać pożyczkę");
        pl.put("bank.loan_id", "ID pożyczki");

        pl.put("help.bank", "§e/ec bank §7- otwiera menu banku");
        pl.put("bank.command.list", "§e/ec bank list §7- pokazuje otwarte prośby i oferty pożyczek");
        pl.put("bank.invalid_target", "§cNieznany gracz docelowy.");
        pl.put("bank.not_enough_money", "§cNie masz wystarczająco pieniędzy.");
        pl.put("bank.not_found", "§cNie znaleziono pożyczki.");
        pl.put("bank.request.created", "§aUtworzono prośbę o pożyczkę.");
        pl.put("bank.offer.created", "§aUtworzono ofertę pożyczki.");
        pl.put("bank.accepted", "§aPożyczka zaakceptowana.");
        pl.put("bank.repaid", "§aPożyczka spłacona.");
        pl.put("history.loan.request", "§bProśba o pożyczkę: $%d");
        pl.put("history.loan.funded", "§aPożyczka sfinansowana: $%d");
        pl.put("history.loan.received", "§aPożyczka otrzymana: $%d");
        pl.put("history.loan.repaid", "§6Pożyczka spłacona: $%d");
        pl.put("history.loan.interest", "§eZapłacone odsetki: $%d");
        pl.put("draft.input.price", "§eWpisz teraz cenę na czacie.");
        pl.put("draft.input.description", "§eWpisz teraz opis na czacie.");
        pl.put("draft.input.built", "§eWpisz teraz, co jest zbudowane na działce.");
        pl.put("draft.input.justification", "§eWpisz teraz uzasadnienie ceny na czacie.");
        pl.put("draft.input.no_draft", "§cNie wybrano szkicu sprzedaży.");
        pl.put("draft.input.price_positive", "§cCena musi być większa niż 0.");
        pl.put("draft.input.invalid_number", "§cTo nie jest poprawna liczba.");
        pl.put("draft.input.price_set", "§aUstawiono cenę szkicu na $%d");
        pl.put("draft.input.description_set", "§aZaktualizowano opis szkicu.");
        pl.put("draft.input.built_set", "§aZaktualizowano tekst zabudowy.");
        pl.put("draft.input.justification_set", "§aZaktualizowano uzasadnienie ceny.");
        pl.put("daily.already", "§cNagroda dzienna została już odebrana. Wróć za %dh %dm.");
        pl.put("daily.claimed", "§aOdebrano codzienne $100.");
        pl.put("pay.known_or_treasury", "§cTylko znani gracze lub skarbiec mogą otrzymać pieniądze.");
        pl.put("pay.self", "§cNie możesz płacić samemu sobie.");
        pl.put("pay.not_enough", "§cNie masz wystarczająco pieniędzy.");
        pl.put("pay.sent", "§aWysłano $%d do %s.");
        pl.put("pay.received", "§aOtrzymano $%d od %s.");
        pl.put("admin.pos1_set", "§aUstawiono capital pos1 na: %d, %d, %d");
        pl.put("admin.pos2_set", "§aUstawiono capital pos2 na: %d, %d, %d");
        pl.put("admin.pos_missing", "§cNajpierw ustaw /ec admin pos1 i /ec admin pos2.");
        pl.put("admin.capital_saved", "§aZapisano obszar stolicy.");
        pl.put("admin.capital_cleared", "§aWyczyszczono obszar stolicy.");

        LANG.put("pl_pl", pl);

        Map<String, String> fr = new HashMap<>(en);
        fr.put("admin.language", "§7Langue : Français");
        fr.put("admin.mode.title", "Mode admin EconomyMC");
        fr.put("common.close", "§cFermer");
        fr.put("common.back", "§cRetour");
        fr.put("common.next", "§7Page suivante");
        fr.put("common.previous", "§7Page précédente");
        fr.put("common.confirm", "§aConfirmer");
        fr.put("common.cancel", "§cAnnuler");
        fr.put("common.create", "§aCréer");
        fr.put("common.edit", "§eModifier");
        fr.put("common.price", "§6Prix");
        fr.put("common.description", "§7Description");
        fr.put("common.status", "§7Statut");
        fr.put("common.page", "§7Page ");
        fr.put("common.seller", "§7Vendeur");
        fr.put("common.amount", "§7Quantité");
        fr.put("common.click_to_view", "§7Cliquer pour voir");
        fr.put("common.publish", "§bPublier");
        fr.put("common.sell", "§aVendre");
        fr.put("menu.player.balance", "§6Solde: $%d");
        fr.put("menu.player.normal", "§7Crédits normaux: %d");
        fr.put("menu.player.capital", "§7Crédits capitale: %d");
        fr.put("plots.menu.title", "EconomyMC Parcelles");
        fr.put("shop.menu.title", "EconomyMC Boutique");
        fr.put("shop.sell.title", "EconomyMC Vendre un objet");
        fr.put("jobs.menu.title", "EconomyMC Jobs");
        fr.put("jobs.server.title", "Jobs serveur EconomyMC");
        fr.put("checks.menu.title", "EconomyMC Chèques");
        fr.put("check.redeem.title", "Encaisser un chèque EconomyMC");
        fr.put("server.mode.title", "Mode serveur EconomyMC");
        fr.put("history.title", "Historique EconomyMC");
        fr.put("bank.title", "Banque EconomyMC");
        fr.put("market.menu.title", "Marché EconomyMC");
        fr.put("myplots.menu.title", "Mes parcelles");
        fr.put("mysales.menu.title", "Mes ventes");
        fr.put("listing.menu.title", "Offre EconomyMC");
        fr.put("help.bank", "§e/ec bank §7- ouvre le menu banque");
        fr.put("bank.command.list", "§e/ec bank list §7- affiche les demandes et offres de prêt ouvertes");
        fr.put("draft.input.price", "§eEntrez maintenant le prix dans le chat.");
        fr.put("draft.input.description", "§eEntrez maintenant la description dans le chat.");
        fr.put("draft.input.built", "§eEntrez maintenant ce qui est construit sur la parcelle.");
        fr.put("draft.input.justification", "§eEntrez maintenant la justification du prix dans le chat.");
        fr.put("draft.input.no_draft", "§cAucun brouillon de vente sélectionné.");
        fr.put("draft.input.price_positive", "§cLe prix doit être supérieur à 0.");
        fr.put("draft.input.invalid_number", "§cCe n'est pas un nombre valide.");
        fr.put("draft.input.price_set", "§aPrix du brouillon défini sur $%d");
        fr.put("draft.input.description_set", "§aDescription du brouillon mise à jour.");
        fr.put("draft.input.built_set", "§aTexte de construction mis à jour.");
        fr.put("draft.input.justification_set", "§aJustification du prix mise à jour.");
        LANG.put("fr_fr", fr);

        Map<String, String> es = new HashMap<>(en);
        es.put("admin.language", "§7Idioma: Español");
        es.put("admin.mode.title", "Modo admin EconomyMC");
        es.put("common.close", "§cCerrar");
        es.put("common.back", "§cAtrás");
        es.put("common.next", "§7Página siguiente");
        es.put("common.previous", "§7Página anterior");
        es.put("common.confirm", "§aConfirmar");
        es.put("common.cancel", "§cCancelar");
        es.put("common.create", "§aCrear");
        es.put("common.edit", "§eEditar");
        es.put("common.price", "§6Precio");
        es.put("common.description", "§7Descripción");
        es.put("common.status", "§7Estado");
        es.put("common.page", "§7Página ");
        es.put("common.seller", "§7Vendedor");
        es.put("common.amount", "§7Cantidad");
        es.put("common.click_to_view", "§7Haz clic para ver");
        es.put("common.publish", "§bPublicar");
        es.put("common.sell", "§aVender");
        es.put("menu.player.balance", "§6Saldo: $%d");
        es.put("menu.player.normal", "§7Créditos normales: %d");
        es.put("menu.player.capital", "§7Créditos capitales: %d");
        es.put("plots.menu.title", "EconomyMC Parcelas");
        es.put("shop.menu.title", "EconomyMC Tienda");
        es.put("shop.sell.title", "EconomyMC Vender objeto");
        es.put("jobs.menu.title", "EconomyMC Trabajos");
        es.put("jobs.server.title", "Trabajos del servidor EconomyMC");
        es.put("checks.menu.title", "EconomyMC Cheques");
        es.put("check.redeem.title", "Canjear cheque EconomyMC");
        es.put("server.mode.title", "Modo servidor EconomyMC");
        es.put("history.title", "Historial EconomyMC");
        es.put("bank.title", "Banco EconomyMC");
        es.put("market.menu.title", "Mercado EconomyMC");
        es.put("myplots.menu.title", "Mis parcelas");
        es.put("mysales.menu.title", "Mis ventas");
        es.put("listing.menu.title", "Oferta EconomyMC");
        es.put("help.bank", "§e/ec bank §7- abre el menú del banco");
        es.put("bank.command.list", "§e/ec bank list §7- muestra solicitudes y ofertas de préstamo abiertas");
        es.put("draft.input.price", "§eIntroduce ahora el precio en el chat.");
        es.put("draft.input.description", "§eIntroduce ahora la descripción en el chat.");
        es.put("draft.input.built", "§eIntroduce ahora qué hay construido en la parcela.");
        es.put("draft.input.justification", "§eIntroduce ahora la justificación del precio en el chat.");
        es.put("draft.input.no_draft", "§cNo hay borrador de venta seleccionado.");
        es.put("draft.input.price_positive", "§cEl precio debe ser mayor que 0.");
        es.put("draft.input.invalid_number", "§cEse no es un número válido.");
        es.put("draft.input.price_set", "§aPrecio del borrador establecido en $%d");
        es.put("draft.input.description_set", "§aDescripción del borrador actualizada.");
        es.put("draft.input.built_set", "§aTexto de construcción actualizado.");
        es.put("draft.input.justification_set", "§aJustificación del precio actualizada.");
        LANG.put("es_es", es);

        Map<String, String> pt = new HashMap<>(en);
        pt.put("admin.language", "§7Idioma: Português");
        pt.put("admin.mode.title", "Modo admin EconomyMC");
        pt.put("common.close", "§cFechar");
        pt.put("common.back", "§cVoltar");
        pt.put("common.next", "§7Próxima página");
        pt.put("common.previous", "§7Página anterior");
        pt.put("common.confirm", "§aConfirmar");
        pt.put("common.cancel", "§cCancelar");
        pt.put("common.create", "§aCriar");
        pt.put("common.edit", "§eEditar");
        pt.put("common.price", "§6Preço");
        pt.put("common.description", "§7Descrição");
        pt.put("common.status", "§7Status");
        pt.put("common.page", "§7Página ");
        pt.put("common.seller", "§7Vendedor");
        pt.put("common.amount", "§7Quantidade");
        pt.put("common.click_to_view", "§7Clique para ver");
        pt.put("common.publish", "§bPublicar");
        pt.put("common.sell", "§aVender");
        pt.put("menu.player.balance", "§6Saldo: $%d");
        pt.put("menu.player.normal", "§7Créditos normais: %d");
        pt.put("menu.player.capital", "§7Créditos da capital: %d");
        pt.put("plots.menu.title", "EconomyMC Terrenos");
        pt.put("shop.menu.title", "EconomyMC Loja");
        pt.put("shop.sell.title", "EconomyMC Vender item");
        pt.put("jobs.menu.title", "EconomyMC Trabalhos");
        pt.put("jobs.server.title", "Trabalhos do servidor EconomyMC");
        pt.put("checks.menu.title", "EconomyMC Cheques");
        pt.put("check.redeem.title", "Resgatar cheque EconomyMC");
        pt.put("server.mode.title", "Modo servidor EconomyMC");
        pt.put("history.title", "Histórico EconomyMC");
        pt.put("bank.title", "Banco EconomyMC");
        pt.put("market.menu.title", "Mercado EconomyMC");
        pt.put("myplots.menu.title", "Meus terrenos");
        pt.put("mysales.menu.title", "Minhas vendas");
        pt.put("listing.menu.title", "Oferta EconomyMC");
        pt.put("help.bank", "§e/ec bank §7- abre o menu do banco");
        pt.put("bank.command.list", "§e/ec bank list §7- mostra pedidos e ofertas de empréstimo abertos");
        pt.put("draft.input.price", "§eDigite agora o preço no chat.");
        pt.put("draft.input.description", "§eDigite agora a descrição no chat.");
        pt.put("draft.input.built", "§eDigite agora o que foi construído no terreno.");
        pt.put("draft.input.justification", "§eDigite agora a justificativa do preço no chat.");
        pt.put("draft.input.no_draft", "§cNenhum rascunho de venda selecionado.");
        pt.put("draft.input.price_positive", "§cO preço deve ser maior que 0.");
        pt.put("draft.input.invalid_number", "§cIsso não é um número válido.");
        pt.put("draft.input.price_set", "§aPreço do rascunho definido para $%d");
        pt.put("draft.input.description_set", "§aDescrição do rascunho atualizada.");
        pt.put("draft.input.built_set", "§aTexto da construção atualizado.");
        pt.put("draft.input.justification_set", "§aJustificativa do preço atualizada.");
        LANG.put("pt_br", pt);

        Map<String, String> ru = new HashMap<>(en);
        ru.put("admin.language", "§7Язык: Русский");
        ru.put("admin.mode.title", "Режим администратора EconomyMC");
        ru.put("common.close", "§cЗакрыть");
        ru.put("common.back", "§cНазад");
        ru.put("common.next", "§7Следующая страница");
        ru.put("common.previous", "§7Предыдущая страница");
        ru.put("common.confirm", "§aПодтвердить");
        ru.put("common.cancel", "§cОтмена");
        ru.put("common.create", "§aСоздать");
        ru.put("common.edit", "§eИзменить");
        ru.put("common.price", "§6Цена");
        ru.put("common.description", "§7Описание");
        ru.put("common.status", "§7Статус");
        ru.put("common.page", "§7Страница ");
        ru.put("common.seller", "§7Продавец");
        ru.put("common.amount", "§7Количество");
        ru.put("common.click_to_view", "§7Нажмите для просмотра");
        ru.put("common.publish", "§bОпубликовать");
        ru.put("common.sell", "§aПродать");
        ru.put("menu.player.balance", "§6Баланс: $%d");
        ru.put("menu.player.normal", "§7Обычные кредиты: %d");
        ru.put("menu.player.capital", "§7Столичные кредиты: %d");
        ru.put("plots.menu.title", "EconomyMC Участки");
        ru.put("shop.menu.title", "EconomyMC Магазин");
        ru.put("shop.sell.title", "EconomyMC Продать предмет");
        ru.put("jobs.menu.title", "EconomyMC Задания");
        ru.put("jobs.server.title", "Серверные задания EconomyMC");
        ru.put("checks.menu.title", "EconomyMC Чеки");
        ru.put("check.redeem.title", "Погасить чек EconomyMC");
        ru.put("server.mode.title", "Серверный режим EconomyMC");
        ru.put("history.title", "История EconomyMC");
        ru.put("bank.title", "Банк EconomyMC");
        ru.put("market.menu.title", "Рынок EconomyMC");
        ru.put("myplots.menu.title", "Мои участки");
        ru.put("mysales.menu.title", "Мои продажи");
        ru.put("listing.menu.title", "Предложение EconomyMC");
        ru.put("help.bank", "§e/ec bank §7- открывает меню банка");
        ru.put("bank.command.list", "§e/ec bank list §7- показывает открытые запросы и предложения займов");
        ru.put("draft.input.price", "§eВведите цену в чат.");
        ru.put("draft.input.description", "§eВведите описание в чат.");
        ru.put("draft.input.built", "§eВведите, что построено на участке.");
        ru.put("draft.input.justification", "§eВведите обоснование цены в чат.");
        ru.put("draft.input.no_draft", "§cЧерновик продажи не выбран.");
        ru.put("draft.input.price_positive", "§cЦена должна быть больше 0.");
        ru.put("draft.input.invalid_number", "§cЭто не корректное число.");
        ru.put("draft.input.price_set", "§aЦена черновика установлена на $%d");
        ru.put("draft.input.description_set", "§aОписание черновика обновлено.");
        ru.put("draft.input.built_set", "§aТекст о постройке обновлён.");
        ru.put("draft.input.justification_set", "§aОбоснование цены обновлено.");
        LANG.put("ru_ru", ru);

        Map<String, String> tr = new HashMap<>(en);
        tr.put("admin.language", "§7Dil: Türkçe");
        tr.put("admin.mode.title", "EconomyMC yönetici modu");
        tr.put("common.close", "§cKapat");
        tr.put("common.back", "§cGeri");
        tr.put("common.next", "§7Sonraki sayfa");
        tr.put("common.previous", "§7Önceki sayfa");
        tr.put("common.confirm", "§aOnayla");
        tr.put("common.cancel", "§cİptal");
        tr.put("common.create", "§aOluştur");
        tr.put("common.edit", "§eDüzenle");
        tr.put("common.price", "§6Fiyat");
        tr.put("common.description", "§7Açıklama");
        tr.put("common.status", "§7Durum");
        tr.put("common.page", "§7Sayfa ");
        tr.put("common.seller", "§7Satıcı");
        tr.put("common.amount", "§7Miktar");
        tr.put("common.click_to_view", "§7Görüntülemek için tıkla");
        tr.put("common.publish", "§bYayınla");
        tr.put("common.sell", "§aSat");
        tr.put("menu.player.balance", "§6Bakiye: $%d");
        tr.put("menu.player.normal", "§7Normal krediler: %d");
        tr.put("menu.player.capital", "§7Başkent kredileri: %d");
        tr.put("plots.menu.title", "EconomyMC Arsalar");
        tr.put("shop.menu.title", "EconomyMC Mağaza");
        tr.put("shop.sell.title", "EconomyMC Eşya sat");
        tr.put("jobs.menu.title", "EconomyMC İşler");
        tr.put("jobs.server.title", "EconomyMC sunucu işleri");
        tr.put("checks.menu.title", "EconomyMC Çekler");
        tr.put("check.redeem.title", "EconomyMC çeki bozdur");
        tr.put("server.mode.title", "EconomyMC sunucu modu");
        tr.put("history.title", "EconomyMC Geçmiş");
        tr.put("bank.title", "EconomyMC Banka");
        tr.put("market.menu.title", "EconomyMC Pazar");
        tr.put("myplots.menu.title", "Arsalarım");
        tr.put("mysales.menu.title", "Satışlarım");
        tr.put("listing.menu.title", "EconomyMC İlanı");
        tr.put("help.bank", "§e/ec bank §7- banka menüsünü açar");
        tr.put("bank.command.list", "§e/ec bank list §7- açık kredi isteklerini ve tekliflerini gösterir");
        tr.put("bank.invalid_target", "§cBilinmeyen hedef oyuncu.");
        tr.put("bank.not_enough_money", "§cYeterli paran yok.");
        tr.put("bank.not_found", "§cKredi bulunamadı.");
        tr.put("bank.request.created", "§aKredi isteği oluşturuldu.");
        tr.put("bank.offer.created", "§aKredi teklifi oluşturuldu.");
        tr.put("bank.accepted", "§aKredi kabul edildi.");
        tr.put("bank.repaid", "§aKredi geri ödendi.");
        tr.put("history.loan.request", "§bKredi isteği: $%d");
        tr.put("history.loan.funded", "§aKredi finanse edildi: $%d");
        tr.put("history.loan.received", "§aKredi alındı: $%d");
        tr.put("history.loan.repaid", "§6Kredi geri ödendi: $%d");
        tr.put("history.loan.interest", "§eÖdenen faiz: $%d");
        tr.put("draft.input.price", "§eŞimdi fiyatı sohbete gir.");
        tr.put("draft.input.description", "§eŞimdi açıklamayı sohbete gir.");
        tr.put("draft.input.built", "§eArsa üzerinde ne yapıldığını şimdi sohbete gir.");
        tr.put("draft.input.justification", "§eŞimdi fiyat gerekçesini sohbete gir.");
        tr.put("draft.input.no_draft", "§cSatış taslağı seçilmedi.");
        tr.put("draft.input.price_positive", "§cFiyat 0'dan büyük olmalı.");
        tr.put("draft.input.invalid_number", "§cBu geçerli bir sayı değil.");
        tr.put("draft.input.price_set", "§aTaslak fiyatı $%d olarak ayarlandı");
        tr.put("draft.input.description_set", "§aTaslak açıklaması güncellendi.");
        tr.put("draft.input.built_set", "§aYapı metni güncellendi.");
        tr.put("draft.input.justification_set", "§aFiyat gerekçesi güncellendi.");
        tr.put("daily.already", "§cGünlük ödül bugün zaten alındı. %dh %dm sonra tekrar gel.");
        tr.put("daily.claimed", "§aGünlük $100 ödülünü aldın.");
        tr.put("pay.known_or_treasury", "§cSadece bilinen oyuncular veya Hazine para alabilir.");
        tr.put("pay.self", "§cKendine ödeme yapamazsın.");
        tr.put("pay.not_enough", "§cYeterli paran yok.");
        tr.put("pay.sent", "§a%s kişisine $%d gönderdin.");
        tr.put("pay.received", "§a%s kişisinden $%d aldın.");
        tr.put("admin.pos1_set", "§aBaşkent pos1 ayarlandı: %d, %d, %d");
        tr.put("admin.pos2_set", "§aBaşkent pos2 ayarlandı: %d, %d, %d");
        tr.put("admin.pos_missing", "§cÖnce /ec admin pos1 ve /ec admin pos2 ayarla.");
        tr.put("admin.capital_saved", "§aBaşkent alanı kaydedildi.");
        tr.put("admin.capital_cleared", "§aBaşkent alanı temizlendi.");
        LANG.put("tr_tr", tr);

        Map<String, String> zh = new HashMap<>(en);
        zh.put("admin.language", "§7语言: 中文");
        zh.put("admin.mode.title", "EconomyMC 管理模式");
        zh.put("common.close", "§c关闭");
        zh.put("common.back", "§c返回");
        zh.put("common.next", "§7下一页");
        zh.put("common.previous", "§7上一页");
        zh.put("common.confirm", "§a确认");
        zh.put("common.cancel", "§c取消");
        zh.put("common.create", "§a创建");
        zh.put("common.edit", "§e编辑");
        zh.put("common.price", "§6价格");
        zh.put("common.description", "§7说明");
        zh.put("common.status", "§7状态");
        zh.put("common.page", "§7第 ");
        zh.put("common.seller", "§7卖家");
        zh.put("common.amount", "§7数量");
        zh.put("common.click_to_view", "§7点击查看");
        zh.put("common.publish", "§b发布");
        zh.put("common.sell", "§a出售");
        zh.put("menu.player.balance", "§6余额: $%d");
        zh.put("menu.player.normal", "§7普通点数: %d");
        zh.put("menu.player.capital", "§7首都点数: %d");
        zh.put("plots.menu.title", "EconomyMC 地块");
        zh.put("shop.menu.title", "EconomyMC 商店");
        zh.put("shop.sell.title", "EconomyMC 出售物品");
        zh.put("jobs.menu.title", "EconomyMC 工作");
        zh.put("jobs.server.title", "EconomyMC 服务器工作");
        zh.put("checks.menu.title", "EconomyMC 支票");
        zh.put("check.redeem.title", "兑换 EconomyMC 支票");
        zh.put("server.mode.title", "EconomyMC 服务器模式");
        zh.put("history.title", "EconomyMC 历史");
        zh.put("bank.title", "EconomyMC 银行");
        zh.put("market.menu.title", "EconomyMC 市场");
        zh.put("myplots.menu.title", "我的地块");
        zh.put("mysales.menu.title", "我的销售");
        zh.put("listing.menu.title", "EconomyMC 列表");
        zh.put("help.bank", "§e/ec bank §7- 打开银行菜单");
        zh.put("bank.command.list", "§e/ec bank list §7- 显示开放的贷款请求和报价");
        zh.put("draft.input.price", "§e现在在聊天中输入价格。");
        zh.put("draft.input.description", "§e现在在聊天中输入描述。");
        zh.put("draft.input.built", "§e现在输入这块地上建了什么。");
        zh.put("draft.input.justification", "§e现在在聊天中输入价格说明。");
        zh.put("draft.input.no_draft", "§c未选择销售草稿。");
        zh.put("draft.input.price_positive", "§c价格必须大于 0。");
        zh.put("draft.input.invalid_number", "§c这不是有效数字。");
        zh.put("draft.input.price_set", "§a草稿价格已设置为 $%d");
        zh.put("draft.input.description_set", "§a草稿描述已更新。");
        zh.put("draft.input.built_set", "§a建筑文本已更新。");
        zh.put("draft.input.justification_set", "§a价格说明已更新。");
        LANG.put("zh_cn", zh);

        Map<String, String> ja = new HashMap<>(en);
        ja.put("admin.language", "§7言語: 日本語");
        ja.put("admin.mode.title", "EconomyMC 管理モード");
        ja.put("common.close", "§c閉じる");
        ja.put("common.back", "§c戻る");
        ja.put("common.next", "§7次のページ");
        ja.put("common.previous", "§7前のページ");
        ja.put("common.confirm", "§a確認");
        ja.put("common.cancel", "§cキャンセル");
        ja.put("common.create", "§a作成");
        ja.put("common.edit", "§e編集");
        ja.put("common.price", "§6価格");
        ja.put("common.description", "§7説明");
        ja.put("common.status", "§7状態");
        ja.put("common.page", "§7ページ ");
        ja.put("common.seller", "§7販売者");
        ja.put("common.amount", "§7数量");
        ja.put("common.click_to_view", "§7クリックして表示");
        ja.put("common.publish", "§b公開");
        ja.put("common.sell", "§a販売");
        ja.put("menu.player.balance", "§6残高: $%d");
        ja.put("menu.player.normal", "§7通常クレジット: %d");
        ja.put("menu.player.capital", "§7首都クレジット: %d");
        ja.put("plots.menu.title", "EconomyMC 区画");
        ja.put("shop.menu.title", "EconomyMC ショップ");
        ja.put("shop.sell.title", "EconomyMC アイテム販売");
        ja.put("jobs.menu.title", "EconomyMC ジョブ");
        ja.put("jobs.server.title", "EconomyMC サーバージョブ");
        ja.put("checks.menu.title", "EconomyMC 小切手");
        ja.put("check.redeem.title", "EconomyMC 小切手を換金");
        ja.put("server.mode.title", "EconomyMC サーバーモード");
        ja.put("history.title", "EconomyMC 履歴");
        ja.put("bank.title", "EconomyMC 銀行");
        ja.put("market.menu.title", "EconomyMC マーケット");
        ja.put("myplots.menu.title", "自分の区画");
        ja.put("mysales.menu.title", "自分の販売");
        ja.put("listing.menu.title", "EconomyMC 出品");
        ja.put("help.bank", "§e/ec bank §7- 銀行メニューを開きます");
        ja.put("bank.command.list", "§e/ec bank list §7- 公開中のローン依頼とオファーを表示します");
        ja.put("draft.input.price", "§e今すぐチャットに価格を入力してください。");
        ja.put("draft.input.description", "§e今すぐチャットに説明を入力してください。");
        ja.put("draft.input.built", "§e区画に何が建っているか今すぐ入力してください。");
        ja.put("draft.input.justification", "§e今すぐチャットに価格の理由を入力してください。");
        ja.put("draft.input.no_draft", "§c販売ドラフトが選択されていません。");
        ja.put("draft.input.price_positive", "§c価格は 0 より大きくする必要があります。");
        ja.put("draft.input.invalid_number", "§c有効な数字ではありません。");
        ja.put("draft.input.price_set", "§aドラフト価格を $%d に設定しました");
        ja.put("draft.input.description_set", "§aドラフトの説明を更新しました。");
        ja.put("draft.input.built_set", "§a建築テキストを更新しました。");
        ja.put("draft.input.justification_set", "§a価格理由を更新しました。");
        LANG.put("ja_jp", ja);
    }

    private LanguageManager() {}

    public static String tr(String key) {
        return tr(AdminSettingsManager.language(), key);
    }

    public static String tr(String lang, String key) {
        Map<String, String> source = LANG.getOrDefault(lang, LANG.get("en_us"));
        return source.getOrDefault(key, LANG.get("en_us").getOrDefault(key, key));
    }

    public static String format(String key, Object... args) {
        return String.format(tr(key), args);
    }

    public static String currentLanguageLabel() {
        return tr("admin.language");
    }
}